name: LEUK TV
favicon: null
layout_spectrum: 0.5896227105986327
typography_spectrum: 0.9428830330725759
title: LEUK TV
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.12803474790416658
  lightness: 0.4823734883684665
  saturation: 0.0011650070082396269
  rhythmicContrast: 0.041532814502716064
purpose: []
